baseurl = "http://jerad.xyz/"  # End your URL with a `/` trailing slash, e.g. `https://example.com/`.
title = "MIND READING IS NOT OK; WITHOUT PERMISSION"
copyright = "content here along with any derivatives from my mind are &copy; 2019 Jerad Acosta. Any shows or products working with my signals from my body are done so without permission."
theme = "academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

publishDir = "docs"

# Enable comments by entering your Disqus shortname
disqusShortname = "irJERAD"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-91420291-1"

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true # false set <a href="xyz.html" target="_blank"> to open all links in new window


[params]
  name = "Jerad Acosta"
  role = "Extracting the Imperative from Data"
  organization = "Trial & mean squared Error"
  organization_url = "irData.ninja"
  gravatar = true  # Get your avatar from Gravatar.com? (true/false)
  avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  email = "ir@jerad.xyz"
  address = "h47 47 Hobson Street Suite 510, Auckland Central Aucklan, 1010 New Zealand"
  phone = "+64 027 531 6179"
  skype = "jeradacosta"

  # Enable Keybase in Contact section by entering your keybase.io username.
  keybase = "irjerad"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Jan 2, 2006"

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  # Highlight.js options
  #   highlight
  #     Enable global source code highlighting?  If false, you can
  #     override it for a particular page in that page's preamble.
  #
  #     Example: highlight = true
  #
  #   highlight_languages
  #     Add support for highlighting additional languages. Support for
  #     languages mentioned here will be included in all pages. You
  #     can also set this variable for a particular page in that
  #     page's preamble.
  #
  #     Example: highlight_languages = ["go", "lisp", "ocaml"]
  #
  #   highlight_style
  #     Choose a different CSS style for highlighting source
  #     code. Setting this option in a page's preamble has no
  #     effect.
  #
  #     Example: highlight_style = "github-gist"
  #
  #   highlight_version
  #     Choose the version of highlight.js you want. Setting this
  #     option in a page's preamble has no effect.
  #
  #     Example: highlight_version = "9.9.0"
  #
  #   For the list of supported languages, styles, and versions, see:
  #   https://cdnjs.com/libraries/highlight.js/
  #
  #   For more info on the highlighting options, see:
  #   https://gcushen.github.io/hugo-academic-demo/post/writing-markdown-latex/#highlighting-options
  highlight = true
  highlight_languages = ["r", "python", "html", "javascript", "css"]
  highlight_style = "github"
  highlight_version = "9.9.0"

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  custom_css = []
  custom_js  = []

  # idea types.
  #   Used to categorize ideas.
  #   The index of the idea type in the list is used as its unique numerical identifier.
  #   The numeric ID is used in a idea's frontmatter to categorize it.
  #   The language can be edited below.
  #   For multi-lingual sites, copy this block to each language section at the end of this file.
  idea_types = [
    'irData',  # 0
    'LinkedIn',  # 1
    'JeradXYZ',  # 2
    'Medium',  # 3
    'Facebook',  # 4
    'Book',  # 5
    'YouTube'  # 6
  ]

  cert_types = [
    'Data', #0
    'IoT', #1
    'Web', #2
    'Business', #3
    'Software', #4
    'Other', #5
  ]

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
  #   youtube, instagram, soundcloud
  #
  #   For email icon, use "fa" icon pack, "envelope" icon, and
  #   "mailto:your@email.com" as the link.
  #
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:ir@Jerad.xyz"

  [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/irJERAD"

  [[params.social]]
    icon = "facebook"
    icon_pack = "fa"
    link = "//facebook.com/jeradacosta"

  [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/irJERAD"

  [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/jeradacosta/"

  [[params.social]]
    icon = "google-plus"
    icon_pack = "fa"
    link = "//plus.google.com/u/0/+JeradAcosta9"


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

##TODO order home page widgets and sub menu content list pages
[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 5

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 10

[[menu.main]]
  name = "Interesting Ideas"
  identifier = "ideation"
  weight = 15

[[menu.main]]
  name = "A special collection"
  parent = "ideation"
  url = "#ideas_selected"
  weight = 20

[[menu.main]]
  name = "All Ideas"
  parent = "ideation"
  url = "#idea"
  weight = 25

[[menu.main]]
  name = "Skills"
  identifier = "Skills"
  weight = 30

[[menu.main]]
  name = "Learning"
  parent = "Skills"
  url = "#learning"
  weight = 31

[[menu.main]]
  name = "Certifications"
  parent = "Skills"
  url = "/certification"
  weight = 32

[[menu.main]]
  name = "Other Content"
  url = "#external_sites"
  weight = 40

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 45

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  idea_source = "idea_types"

# Languages
#   Create a [languages.X] block for each language you want, where X is the language ID.

# Configure the English version of the website.
[Languages.en]
  languageCode = "en-us"
